set(_CATKIN_CURRENT_PACKAGE "low_level_control")
set(low_level_control_VERSION "0.0.0")
set(low_level_control_MAINTAINER "savio <savio@todo.todo>")
set(low_level_control_PACKAGE_FORMAT "1")
set(low_level_control_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(low_level_control_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(low_level_control_BUILDTOOL_DEPENDS "catkin")
set(low_level_control_BUILDTOOL_EXPORT_DEPENDS )
set(low_level_control_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(low_level_control_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(low_level_control_TEST_DEPENDS )
set(low_level_control_DOC_DEPENDS )
set(low_level_control_DEPRECATED "")