<?xml version="1.0" ?>
<sdf version="1.4">
  <world name="default" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- A global light source -->
    <include>
      <uri>model://sun</uri>
    </include>

    <!-- A ground plane -->
    <include>
      <uri>model://ground_plane</uri>
    </include>

    <gui>
      <camera name="user_camera">
        <pose>72 -32 4 0 0.3 ${3 * pi / 4}</pose>
      </camera>
    </gui>

    <!-- Field -->
    <model name="ground">
      <pose>0 0 0 0 0 0</pose>
      <static>true</static>
      <link name="link">
        <collision name="ground_collision">
          <geometry>
            <box>
              <size>160.0 80.0 0.15</size>
            </box>
          </geometry>
        </collision>
        <visual name="ground_visual">
          <geometry>
            <box>
              <size>160.0 80.0 0.15</size>
              <!-- <size>160.0 80.0 0.15</size> -->
            </box>
          </geometry>
          <material>
            <script>
              <uri>$(find mbzirc_gazebo)/worlds/materials/scripts</uri>
              <uri>$(find mbzirc_gazebo)/worlds/materials/textures</uri>
              <name>MbzircArenaGround/Image</name>
            </script>
          </material>
        </visual>
      </link>
    </model>

    <xacro:macro name="border_segment" params="length x_pos y_pos z_rot">
      <model name="border_segment_${length}_${x_pos}_${y_pos}_${z_rot}">
        <pose>${x_pos} ${y_pos} 0.08 0 0 ${z_rot}</pose>
        <static>true</static>
        <link name="link">
          <visual name="border_segment_${length}_${x_pos}_${y_pos}_${z_rot}_visual">
            <geometry>
              <box>
                <size>${length} 0.1 0.01</size>
              </box>
            </geometry>
            <material>
              <ambient>1 1 1 1</ambient>
              <diffuse>1 1 1 1</diffuse>
              <specular>0.1 0.1 0.1 1</specular>
              <emissive>0 0 0 0</emissive>
            </material>
          </visual>
        </link>
      </model>
    </xacro:macro>

    <xacro:macro name="border" params="length width x_pos y_pos">
      <xacro:border_segment length="${length}" x_pos="${x_pos}" y_pos="${y_pos + width / 2}" z_rot="0" />
      <xacro:border_segment length="${width}" x_pos="${x_pos + length / 2}" y_pos="${y_pos}" z_rot="${pi / 2}" />
      <xacro:border_segment length="${length}" x_pos="${x_pos}" y_pos="${y_pos - width / 2}" z_rot="0" />
      <xacro:border_segment length="${width}" x_pos="${x_pos - length / 2}" y_pos="${y_pos}" z_rot="${pi / 2}" />
    </xacro:macro>

    <xacro:border length="100" width="60" x_pos="0" y_pos="0" />
    <xacro:border length="10" width="10" x_pos="65" y_pos="-25" />
    <xacro:border length="10" width="10" x_pos="-65" y_pos="25" />

  </world>
</sdf>
